local cmd_name_map = {
	"GuestLoginReq",
	"GuestLoginRes",
	"Relogin",
	"UserLostConn",
	"EditProfileReq",
	"EditProfileRes",
	"AccountUpgradeReq",
	"AccountUpgradeRes",
	"UnameLoginReq",
	"UnameLoginRes",
	"LoginOutReq",
	"LoginOutRes",
	"UserRegistReq",
	"UserRegistRes",
	"GetUgameInfoReq",
	"GetUgameInfoRes",
	"RecvLoginBonuesReq",
	"RecvLoginBonuesRes",
	"GetWorldRankUchipReq",
	"GetWorldRankUchipRes",
	"GetSysMsgReq",
	"GetSysMsgRes",
	"LoginLogicReq",
	"LoginLogicRes",
		
	"EnterZoneReq",
	"EnterZoneRes",
	"EnterMatch",
	"UserArrived",
	"ExitMatchReq",
	"ExitMatchRes",
	"UserExitMatch",

	"CreateRoomReq",
	"CreateRoomRes",
	"JoinRoomReq",
	"JoinRoomRes",
	"ExitRoomReq",
	"ExitRoomRes",
	"DessolveReq",
	"DessolveRes",

	"GameStart",
}

return cmd_name_map
